package edu.tjdz.blog.beans.bean;

import java.io.Serializable;

public class Article implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_id
     *
     * @mbg.generated Thu Nov 25 14:17:15 CST 2021
     */
    private Integer articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.title
     *
     * @mbg.generated Thu Nov 25 14:17:15 CST 2021
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_img
     *
     * @mbg.generated Thu Nov 25 14:17:15 CST 2021
     */
    private String articleImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.content
     *
     * @mbg.generated Thu Nov 25 14:17:15 CST 2021
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table article
     *
     * @mbg.generated Thu Nov 25 14:17:15 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Thu Nov 25 14:17:15 CST 2021
     */
    public Article(Integer articleId, String title, String articleImg, String content) {
        this.articleId = articleId;
        this.title = title;
        this.articleImg = articleImg;
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Thu Nov 25 14:17:15 CST 2021
     */
    public Article() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_id
     *
     * @return the value of article.article_id
     *
     * @mbg.generated Thu Nov 25 14:17:15 CST 2021
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_id
     *
     * @param articleId the value for article.article_id
     *
     * @mbg.generated Thu Nov 25 14:17:15 CST 2021
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.title
     *
     * @return the value of article.title
     *
     * @mbg.generated Thu Nov 25 14:17:15 CST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.title
     *
     * @param title the value for article.title
     *
     * @mbg.generated Thu Nov 25 14:17:15 CST 2021
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_img
     *
     * @return the value of article.article_img
     *
     * @mbg.generated Thu Nov 25 14:17:15 CST 2021
     */
    public String getArticleImg() {
        return articleImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_img
     *
     * @param articleImg the value for article.article_img
     *
     * @mbg.generated Thu Nov 25 14:17:15 CST 2021
     */
    public void setArticleImg(String articleImg) {
        this.articleImg = articleImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.content
     *
     * @return the value of article.content
     *
     * @mbg.generated Thu Nov 25 14:17:15 CST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.content
     *
     * @param content the value for article.content
     *
     * @mbg.generated Thu Nov 25 14:17:15 CST 2021
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Thu Nov 25 14:17:15 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", articleId=").append(articleId);
        sb.append(", title=").append(title);
        sb.append(", articleImg=").append(articleImg);
        sb.append(", content=").append(content);
        sb.append("]");
        return sb.toString();
    }
}