package edu.tjdz.blog.beans.bean;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.util.Date;
import java.util.List;


@Data
@NoArgsConstructor
@AllArgsConstructor
public class Comment implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_id
     *
     * @mbg.generated Thu Nov 25 14:17:15 CST 2021
     */
    private Integer commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_content
     *
     * @mbg.generated Thu Nov 25 14:17:15 CST 2021
     */
    private String commentContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.tourist_name
     *
     * @mbg.generated Thu Nov 25 14:17:15 CST 2021
     */
    private String touristName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.tourist_img
     *
     * @mbg.generated Thu Nov 25 14:17:15 CST 2021
     */
    private String touristImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.email
     *
     * @mbg.generated Thu Nov 25 14:17:15 CST 2021
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.cre_time
     *
     * @mbg.generated Thu Nov 25 14:17:15 CST 2021
     */
    private Date creTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.reply_time
     *
     * @mbg.generated Thu Nov 25 14:17:15 CST 2021
     */
    private Date replyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comment
     *
     * @mbg.generated Thu Nov 25 14:17:15 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Thu Nov 25 14:17:15 CST 2021
     */

    private Integer level;

    private Integer articleId;

    private Integer parentId;

    private String parentName;

    private List<Comment> comments;
}