package edu.tjdz.blog.beans.bean;

import java.io.Serializable;

public class Type implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.type_id
     *
     * @mbg.generated Thu Nov 25 14:17:15 CST 2021
     */
    private Integer typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.type
     *
     * @mbg.generated Thu Nov 25 14:17:15 CST 2021
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table type
     *
     * @mbg.generated Thu Nov 25 14:17:15 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type
     *
     * @mbg.generated Thu Nov 25 14:17:15 CST 2021
     */
    public Type(Integer typeId, String type) {
        this.typeId = typeId;
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type
     *
     * @mbg.generated Thu Nov 25 14:17:15 CST 2021
     */
    public Type() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.type_id
     *
     * @return the value of type.type_id
     *
     * @mbg.generated Thu Nov 25 14:17:15 CST 2021
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.type_id
     *
     * @param typeId the value for type.type_id
     *
     * @mbg.generated Thu Nov 25 14:17:15 CST 2021
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.type
     *
     * @return the value of type.type
     *
     * @mbg.generated Thu Nov 25 14:17:15 CST 2021
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.type
     *
     * @param type the value for type.type
     *
     * @mbg.generated Thu Nov 25 14:17:15 CST 2021
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type
     *
     * @mbg.generated Thu Nov 25 14:17:15 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", typeId=").append(typeId);
        sb.append(", type=").append(type);
        sb.append("]");
        return sb.toString();
    }
}